openapi: 3.0.3
info:
  title: EverHungry
  version: "1.0"
  x-logo:
    url: ""
servers:
- url: https://api.example.io
paths: {}
components:
  headers: {}
  parameters: {}
  responses: {}
  schemas: {}
  securitySchemes: {}
